### PR TITLE
Update post-purchase template readme

### PR DESCRIPTION
**Pull request by joeyfreund**
Fix https://github.com/Shopify/argo-private/issues/1469

If you're reviewing this PR, it might be easier for you read the content at https://github.com/Shopify/argo-checkout-template/blob/joeyfreund-post-purchase-readme/scripts/generate/templates/post-purchase/files/README.md

### CODE REVIEW

**Comment by joeyfreund** [comment]
PR implicitly approved ✅  by @andyhealey26 over Slack.

I'm merging this and, if there are any issues, we'll just update the text in follow-up PRs.

**Comment by pauldowman** [comment]
This is a great improvement and probably good enough for an external audience (for now until it's launched) but should it go a bit further, especially for internal audience? I assume you went through [this from the dev handbook](https://development.shopify.io/engineering/overview/culture/knowledge/readmes), are there sections from the README template that might be useful?

**Comment by lemonmade** [comment]
@pauldowman I definitely agree we could beef up documentation, but I don't think we should spend any more time doing it in this repo. https://github.com/Shopify/argo-checkout will probably become https://github.com/Shopify/argo and that will be the place we should guide people to. Honestly, I don't think it is the right approach to have a repo for our templates at all — it means you need to be connected to the internet to initialize a new project, it has some really weird implications for dependencies (our templates basically come out with incorrect lockfiles), and it creates a massive disconnect between the thing that generates the templates (the CLI) and where the templates actually live.

**Comment by pauldowman** [comment]
I'm fine with leaving it. Are you on the same page with the Argo team about the other details in your comment?

**Pull request merged**
